Repository ranger/ranger, pull requests merged in 2018-09, with the labels that each got.

#1285 Add support for default terminal word-movement commands to console
  doc/ranger.1
  doc/ranger.pod
  ranger/config/rc.conf
Labels: next-release

#1294 Add mapping to open console and pre-fill it with previous command
  doc/ranger.1
  doc/ranger.pod
  ranger/config/rc.conf
Labels: enhancement, next-release

#1279 Add the %any_path macro
  ranger/core/actions.py
Labels: next-release

#1276 Implement image previewing for archive files
  ranger/data/scope.sh
Labels: next-release

#1273 Add selection argument to move action
  ranger/core/actions.py
Labels: next-release

#1228 Update plugin_pmount.py
  examples/plugin_pmount_dynamic.py
Labels: next-release

#1109 Attempt to fix issue #1108 flag t problem
  ranger/config/rifle.conf
  ranger/ext/rifle.py
Labels: needs-testing, next-release
