Repository ranger/ranger, pull requests merged in 2019-12, with the labels that each got.

#1368 Exit if STDIN is closed #1367
  ranger/gui/ui.py
Labels: next-release

#1746 port automatic_cd to fish, fix #960
  examples/fish_automatic_cd.fish
Labels: enhancement

#1703 Pass surrogates when listing files for bulkrename
  ranger/config/commands.py
Labels: bug

#1576 Add preview support for .rtf, .doc, .docx, .xlsx, .xls in scope.sh
  ranger/data/scope.sh
Labels: next-release
