Repository ranger/ranger, pull requests merged in 2021-09, with the labels that each got.

#2443 Drop open23
  ranger/config/commands.py
  ranger/container/bookmarks.py
  ranger/container/tags.py
  ranger/core/actions.py
  ranger/core/fm.py
  ranger/core/loader.py
  ranger/core/main.py
  ranger/core/metadata.py
  ranger/core/runner.py
  ranger/ext/open23.py
  ranger/ext/popen_forked.py
  ranger/ext/spawn.py
  ranger/ext/vcs/vcs.py
  ranger/gui/colorscheme.py
  ranger/gui/widgets/console.py
Labels: bug

#1680 Make setlocal path=... argument a regex again
  doc/ranger.1
  doc/ranger.pod
  ranger/config/commands.py
  ranger/container/settings.py
Labels: bug

#2447 Adds a preview for ELF files using readelf
  ranger/data/scope.sh
Labels: enhancement

#2455 HACKING: Drop hut's email and PGP key
  HACKING.md
Labels: doc-issue
