Repository ranger/ranger, pull requests merged in 2021-08, with the labels that each got.

#2410 Process forking was broken when satisfying pylint's consider-using-with
  ranger/ext/img_display.py
  ranger/ext/popen23.py
  ranger/ext/popen_forked.py
  ranger/ext/rifle.py
  ranger/ext/spawn.py
  tests/pylint/py2_compat.py
  tests/pylint/test_py2_compat.py
Labels: bug

#2340 Update README and man page with Libera webchat
  README.md
  doc/ranger.1
  doc/ranger.pod
Labels: enhancement, doc-issue

#2427 Fix command `du` on macOS
  examples/rc_emacs.conf
  ranger/config/rc.conf
Labels: enhancement

#2425 Added support for Right-To-Left languages in the title bar
  ranger/gui/displayable.py
  ranger/gui/widgets/browsercolumn.py
  ranger/gui/widgets/titlebar.py
Labels: enhancement

#2438 ui: Fix crash when TMUX not in environment
  ranger/gui/ui.py
Labels: bug

#2435 fix w3m method in 32bit
  ranger/ext/img_display.py
Labels: bug
