Repository ranger/ranger, pull requests merged in 2023-03, with the labels that each got.

#2001 Gracefully fallback when file(1) is not available to identify mime-type
  ranger/ext/rifle.py
Labels: bug

#2801 Fix Python 2 support related to Subprocess
  ranger/ext/img_display.py
  ranger/ext/rifle.py
Labels: bug

#2750 img_display: Restore cleanup of Kitty tempfiles
  ranger/ext/img_display.py
Labels: bug, image-preview

#2691 Fix image display for palette images with transparency
  ranger/ext/img_display.py
Labels: bug, image-preview

#2542 Make display of directory size in linemodes less misleading
  ranger/core/linemode.py
Labels: bug

#2797 Remove the legacy filename filters, replace them with a compatibility layer utilizing the filter stack
  ranger/config/commands.py
  ranger/container/directory.py
  ranger/core/filter_stack.py
Labels: enhancement

#2813 Support Expansion Of Environment Variables in cd command
  ranger/config/commands.py
Labels: enhancement

#2816 get_executables: Use platform instead of reading /proc
  ranger/ext/get_executables.py
Labels: bug

#2216 Feat: add preview handler for SQLite to scope.sh
  README.md
  doc/ranger.1
  doc/ranger.pod
  ranger/data/scope.sh
Labels: enhancement
