Repository ranger/ranger, pull requests merged in 2025-01, with the labels that each got.

#3037 README: Update version, forge-agnostic URL and center logo
  README.md
Labels: doc-issue

#3039 Adapt to NCurses endwin() error behavior
  ranger/gui/ui.py
Labels: bug

#2445 Feat: ANSI escape codes support for browsercolumn
  ranger/gui/ansi.py
  ranger/gui/widgets/browsercolumn.py
Labels: enhancement

#3042 Avoid running older Pylint with Pypy
  .github/workflows/pypy.yml
Labels: enhancement

#3041 Fix positional argument calls
  ranger/core/actions.py
  ranger/core/runner.py
Labels: bug
